### PR TITLE
Add info about Wakelock app to keep tv on during sleep.

### PR DESCRIPTION
**Pull request by mad-ady**
Tested with Philips "The One" 7304 TV with wired connection.

### CODE REVIEW

**Comment by aegjoyce** [comment]
This worked fantastically for me too. I only used the ‘processor’ setting because I have an OLED804 and was concerned about not turning the screen off fully and if it would disrupt the OLED screen burn prevention mechanisms - still works perfectly

**Comment by liveware-problems** [comment]
How do you install this from Github on a Philips TV? The version in the Play Store isn't compatible with my Philips TV.

**Comment by mad-ady** [comment]
You can download the apk and sideload it to your TV. There are two ways:
1. Enable developer tools and turn on adb on the TV. Then you can use adb
install wakelock.apk.
2. Transfer the APK on the TV via a USB drive and use a file manager to
install it.

You will also need a program launcher like
https://play.google.com/store/apps/details?id=eu.chainfire.tv.sideloadlauncher&hl=en
to launch it.

**Comment by nstrelow** [comment]
Shouldn't this increase power consumption?
Just wondering if this is an issue

**Comment by mad-ady** [comment]
Most likely, yes, it increases power consumption. And may prematurely cause
your TV hardware to age/fail.

However, if power consumption is not a concern, I'd like to address the
other topic. I've been running a Samsung H6400 TV with a similar bypass, so
that it doesn't go to sleep when turned off, for about 4 years now. The TV
is rooted and the power signal is hijacked and turns off only the panel. I
haven't had issues with it, so - most likely heat doesn't cause massive
degradation in the TV's life span.
TVs (higher end) are already designed to be always on (for show rooms,
etc), so their electronics should be able to bear the stress. And also the
SoCs used should support adaptive frequency scaling.

On my Philips ATV I have:
```
PH9M_EA_5599:/ $ uptime
 17:13:43 up 18 days, 19:09,  0 users,  load average: 29.10, 29.35, 29.48
PH9M_EA_5599:/ $ cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
interactive
PH9M_EA_5599:/ $ cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq

1500000
PH9M_EA_5599:/ $ cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_min_freq

1032000
PH9M_EA_5599:/ $ cat sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq
                       <
cat: /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq: Permission
denied
```
So, it should be throttling down (to 1GHz in my case) the SoC frequency
when idle. I don't know what the deal is with the huge load on the system,
but I'm guessing there might be some unoptimized kernel drivers that use
polling or something and artificially increase the load.

**Comment by liveware-problems** [comment]
Many thanks @mad-ady -I installed the Downloader app (used on FireTV sticks) to grab the APK and install it on the TV; hadn't thought about needing a sideload launcher though! Looks to be doing the trick so far - the ambilight had kept going 'unavailable' a few minutes after the TV was switched off, but not any more.

**Pull request merged**
